import React from 'react';

import SiteHeader from 'components/site/Header';
import SiteFooter from 'components/site/Footer';

import Container from '@mui/material/Container';

export default function PrivacyPolicy() {
	return (
		<>
			<SiteHeader />

			<div className='common-bg mb-4'>
				<Container className='text-gray-800 list-ul-p-[20px]'>
					<div className='pt-20 md:pt-24 pb-10 text-center'>
						<div className='font-bold text-dark-blue md:text-7xl text-5xl'>Privacy and Policy</div>
					</div>
					<div className='text-base mb-20'>
						Lacuna Labs Sdn. Bhd. ("us", "we", or "our") operates the http://ombre.app website and the Ombré mobile application (the
						"Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use
						our Service and the choices you have associated with that data.
						<br />
						<br />
						We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information
						in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the
						same meanings as in our Terms and Conditions.
					</div>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Definitions</p>

					<ul className='marker:text-dark-yellow text-[24px] mb-20'>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Service</p>
							<p className='text-base'>
								Service means the http://ombre.app website and the Ombré mobile application operated by Lacuna Labs Sdn Bhd.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Personal Data</p>
							<p className='text-base'>
								Personal Data means data about a living individual who can be identified from those data (or from those and other
								information either in our possession or likely to come into our possession).
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Usage Data</p>
							<p className='text-base'>
								Usage Data is data collected automatically either generated by the use of the Service or from the Service
								infrastructure itself (for example, the duration of a page visit).
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Cookies</p>
							<p className='text-base'>Cookies are small pieces of data stored on your device (computer or mobile device).</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Data Controller</p>
							<p className='text-base'>
								Data Controller means the natural or legal person who (either alone or jointly or in common with other persons)
								determines the purposes for which and the manner in which any personal information are, or are to be, processed. For
								the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Data Processors (Or Service Providers)</p>
							<p className='text-base'>
								Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data
								Controller. We may use the services of various Service Providers in order to process your data more effectively.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Data Subject (Or User)</p>
							<p className='text-base'>
								Data Subject is any living individual who is using our Service and is the subject of Personal Data.
							</p>
						</li>
					</ul>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Information Collection and use Types of Data Collected</p>
					<p className='text-base mb-4'>
						We collect several different types of information for various purposes to provide and improve our Service to you.
					</p>

					<ul className='marker:text-dark-yellow text-[24px] mb-20'>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Personal Data</p>
							<p className='text-base'>
								While using our Service, we may ask you to provide us with certain personally identifiable information that can be
								used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited
								to: email address, first name and last name, phone number, address, state, province, ZIP/postal code, city, cookies
								and usage data.
								<br />
								We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other
								information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us
								by following the unsubscribe link or instructions provided in any email we send.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Usage Data</p>
							<p className='text-base'>
								We may also collect information that your browser sends whenever you visit our Service or when you access the Service
								by or through a mobile device ("Usage Data").
								<br />
								This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser
								type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on
								those pages, unique device identifiers and other diagnostic data.
								<br />
								When you access the Service by or through a mobile device, this Usage Data may include information such as the type of
								mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating
								system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Location Data</p>
							<p className='text-base'>
								We may use and store information about your location if you give us permission to do so (“Location Data”). We use this
								data to provide features of our Service, to improve and customize our Service.
								<br />
								You can enable or disable location services when you use our Service at any time, through your device settings.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Tracking and Cookies Data</p>
							<p className='text-base'>
								We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
								<br />
								Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your
								browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to
								collect and track information and to improve and analyze our Service.
								<br />
								You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not
								accept cookies, you may not be able to use some portions of our Service.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Examples of Cookies we use:</p>
							<ul className='marker:text-gray-900 list-disc text-[16px]'>
								<li>
									<p className='text-base'>Session Cookies. We use Session Cookies to operate our Service.</p>
								</li>
								<li>
									<p className='text-base'>
										Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
									</p>
								</li>
								<li>
									<p className='text-base'>Security Cookies. We use Security Cookies for security purposes.</p>
								</li>
								<li>
									<p className='text-base'>
										Advertising Cookies. Advertising Cookies are used to serve you with advertisements that may be relevant to you
										and your interests.
									</p>
								</li>
							</ul>
						</li>
					</ul>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Use of Data</p>
					<p className='text-base mb-4'>Lacuna Labs Sdn Bhd uses the collected data for various purposes:</p>
					<ul className='marker:text-dark-yellow text-[24px] mb-20'>
						<li>
							<p className='text-base'>To provide and maintain our Service</p>
						</li>
						<li>
							<p className='text-base'>To notify you about changes to our Service</p>
						</li>
						<li>
							<p className='text-base'>To allow you to participate in interactive features of our Service when you choose to do so</p>
						</li>
						<li>
							<p className='text-base'>To provide customer support</p>
						</li>
						<li>
							<p className='text-base'>To gather analysis or valuable information so that we can improve our Service</p>
						</li>
						<li>
							<p className='text-base'>To monitor the usage of our Service</p>
						</li>
						<li>
							<p className='text-base'>To detect, prevent and address technical issues</p>
						</li>
						<li>
							<p className='text-base'>
								To provide you with news, special offers and general information about other goods, services and events which we offer
								that are similar to those that you have already purchased or enquired about unless you have opted not to receive such
								information
							</p>
						</li>
					</ul>

					<p className='font-bold text-blue-600 text-3xl mb-4'>
						Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)
					</p>
					<p className='text-base mb-4'>
						If you are from the European Economic Area (EEA), Lacuna Labs Sdn Bhd legal basis for collecting and using the personal
						information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we
						collect it. Lacuna Labs Sdn Bhd may process your Personal Data because:
					</p>

					<ul className='marker:text-dark-yellow text-[24px] mb-20'>
						<li>
							<p className='text-base'>We need to perform a contract with you</p>
						</li>
						<li>
							<p className='text-base'>You have given us permission to do so</p>
						</li>
						<li>
							<p className='text-base'>The processing is in our legitimate interests and it's not overridden by your rights</p>
						</li>
						<li>
							<p className='text-base'>For payment processing purposes</p>
						</li>
						<li>
							<p className='text-base'>To comply with the law</p>
						</li>
					</ul>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Reservation of rights</p>
					<p className='text-base mb-4'>
						Lacuna Labs Sdn Bhd will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy
						Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example,
						if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and
						policies.
					</p>
					<p className='text-base mb-20'>
						Lacuna Labs Sdn Bhd will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter
						period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we
						are legally obligated to retain this data for longer time periods.
					</p>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Retention of Data</p>
					<p className='text-base mb-4'>
						Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your
						state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your
						jurisdiction.
					</p>
					<p className='text-base mb-4'>
						If you are located outside Malaysia and choose to provide information to us, please note that we transfer the data, including
						Personal Data, to Malaysia and process it there.
					</p>
					<p className='text-base mb-20'>
						Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that
						transfer. Lacuna Labs Sdn Bhd will take all steps reasonably necessary to ensure that your data is treated securely and in
						accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country
						unless there are adequate controls in place including the security of your data and other personal information.
					</p>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Disclosure of Data</p>
					<ul className='marker:text-dark-yellow text-[24px] mb-20'>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Business Transaction</p>
							<p className='text-base'>
								If Lacuna Labs Sdn Bhd is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We
								will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Disclosure for Law Enforcement</p>
							<p className='text-base'>
								Under certain circumstances, Lacuna Labs Sdn Bhd may be required to disclose your Personal Data if required to do so
								by law or in response to valid requests by public authorities (e.g. a court or a government agency).
							</p>
						</li>
						<li className='mb-4'>
							<p className='font-bold text-blue-600 text-xl'>Legal Requirements</p>
							<p className='text-base'>
								Lacuna Labs Sdn Bhd may disclose your Personal Data in the good faith belief that such action is necessary to:
							</p>
							<ul className='marker:text-gray-900 list-disc text-[16px]'>
								<li>
									<p className='text-base'>To comply with a legal obligation</p>
								</li>
								<li>
									<p className='text-base'>To protect and defend the rights or property of Lacuna Labs Sdn Bhd</p>
								</li>
								<li>
									<p className='text-base'>To prevent or investigate possible wrongdoing in connection with the Service</p>
								</li>
								<li>
									<p className='text-base'>To protect the personal safety of users of the Service or the public</p>
								</li>
								<li>
									<p className='text-base'>To protect against legal liability</p>
								</li>
							</ul>
						</li>
					</ul>

					<p className='font-bold text-blue-600 text-3xl mb-4'>
						Data Security "Do Not Track" Signals Under California Online Privacy Protection Act (CalOPPA) Service Providers
					</p>
					<p className='text-base mb-4'>
						Your data security is important to us, but remember that no method of transmission over the Internet, or method of electronic
						storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot
						guarantee its absolute security.
					</p>
					<ul className='marker:text-dark-yellow text-[24px] mb-20'>
						<li className='mb-4'>
							<p className='text-base'>
								We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform
								websites that you do not want to be tracked.
							</p>
						</li>
						<li className='mb-4'>
							<p className='text-base'>
								You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
								<br />
								We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the
								Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used. These
								third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to
								disclose or use it for any other purpose.
							</p>
						</li>
						<li className='mb-4'>
							<p className='text-base mb-2'>
								Analytics
								<br />
								We may use third-party Service Providers to monitor and analyze the use of our Service.
							</p>
							<ul className='marker:text-gray-900 list-disc text-[16px]'>
								<li>
									<p className='text-base'>
										Google Analytics. Google Analytics is a web analytics service offered by Google that tracks and reports
										website traffic. Google uses the data collected to track and monitor the use of our Service. This data is
										shared with other Google services. Google may use the collected data to contextualize and personalize the ads
										of its own advertising network.
									</p>
								</li>
								<li>
									<p className='text-base'>
										Flurry Analytics. Flurry Analytics service is provided by Yahoo! Inc. You can opt-out from Flurry Analytics
										service to prevent Flurry Analytics from using and sharing your information by visiting the Flurry's Opt-out
										page.
									</p>
								</li>
								<li>
									<p className='text-base'>
										Mixpanel. Mixpanel is provided by Mixpanel Inc You can prevent Mixpanel from using your information for
										analytics purposes by opting-out.
									</p>
								</li>
							</ul>
						</li>
						<li className='mb-4'>
							<p className='text-base mb-2'>
								Advertising
								<br />
								We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.
							</p>
							<ul className='marker:text-gray-900 list-disc text-[16px]'>
								<li>
									<p className='text-base'>
										Google AdSense & DoubleClick Cookie. Google, as a third party vendor, uses cookies to serve ads on our
										Service. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on
										their visit to our Service or other websites on the Internet.
									</p>
								</li>
								<li>
									<p className='text-base'>Bing Ads. Bing Ads is an advertising service provided by Microsoft, Inc.</p>
								</li>
								<li>
									<p className='text-base'>AdMob by Google. AdMob by Google is provided by Google Inc.</p>
								</li>
								<li>
									<p className='text-base'>Flurry. Flurry is provided by Yahoo! Inc.</p>
								</li>
							</ul>
						</li>
						<li className='mb-4'>
							<p className='text-base mb-2'>
								Behavioural Remarketing
								<br />
								Lacuna Labs Sdn Bhd uses remarketing services to advertise on third party websites to you after you visited our
								Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our
								Service.
							</p>
							<ul className='marker:text-gray-900 list-disc text-[16px] mb-2'>
								<li>
									<p className='text-base'>
										Google AdWords. Google AdWords remarketing service is provided by Google Inc. Google aecommends installing the
										Google Analytics Opt-out Browser Add-on. Google Analytics Opt-out Browser Add-on provides visitors with the
										ability to prevent their data from being collected and used by Google Analytics.
									</p>
								</li>
								<li>
									<p className='text-base'>Twitter. Twitter remarketing service is provided by Twitter Inc.</p>
								</li>
								<li>
									<p className='text-base'>
										Facebook. Facebook remarketing service is provided by Facebook Inc. Facebook adheres to the Self-Regulatory
										Principles for Online Behavioral.
									</p>
								</li>
							</ul>
							<p className='text-base'>
								Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other
								participating companies through the Digital Advertising Alliance in the USA, the Digital Advertising Alliance of
								Canada in Canada or the European Interactive Digital Advertising Alliance in Europe, or opt-out using your mobile
								device settings.
							</p>
						</li>
						<li className='mb-4'>
							<p className='text-base mb-2'>
								Payments
								<br />
								We may provide paid products and/or services within the Service. In that case, we use third-party services for payment
								processing (e.g. payment processors). We will not store or collect your payment card details. That information is
								provided directly to our third-party payment processors whose use of your personal information is governed by their
								Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security
								Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS
								requirements help ensure the secure handling of payment information. The payment processors we work with are:
							</p>
							<ul className='marker:text-gray-900 list-disc text-[16px] mb-2'>
								<li>
									<p className='text-base'>Apple Store In-App Payments</p>
								</li>
								<li>
									<p className='text-base'>Google Play In-App Payments</p>
								</li>
								<li>
									<p className='text-base'>Stripe</p>
								</li>
								<li>
									<p className='text-base'>PayPal or Braintree</p>
								</li>
							</ul>
						</li>
					</ul>

					<p className='font-bold text-blue-600 text-3xl mb-4'>Links to Other Sites Changes to this Privacy Policy Contact Us</p>
					<p className='text-base'>
						Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be
						directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no
						control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
					</p>
					<p className='text-base pb-20'>
						We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on
						this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and
						update the "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for
						any changes. Changes to this Privacy Policy are effective when they are posted on this page. If you have any questions about
						this Privacy Policy, please contact us via email at hello@ombre.app
					</p>
				</Container>
			</div>

			<SiteFooter />
		</>
	);
}
